Vagrant.configure("2") do |config|
  
  config.vm.define "dev" do |dev|
  	dev.vm.box = "centos/7"
  	dev.vm.provision "shell", path: "dev-working-env.sh"
  	dev.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "git" do |git|
  	git.vm.box = "centos/7"
  	git.vm.provision "shell", path: "git.sh"
  	git.vm.network "private_network", ip: "192.168.33.20"
  end

  config.vm.define "jenkins" do |jenkins|
  	jenkins.vm.box = "centos/7"
  	jenkins.vm.provision "shell", path: "jenkins.sh"
  	jenkins.vm.network "private_network", ip: "192.168.33.30"
  	jenkins.vm.network "forwarded_port", guest: 6060, host: 6060
  end

  config.vm.define "sonar" do |sonar|
  	sonar.vm.box = "centos/7"
  	sonar.vm.provision "shell", path: "sonar.sh"
  	sonar.vm.network "private_network", ip: "192.168.33.40"
  	sonar.vm.network "forwarded_port", guest: 9000, host: 9000
  end

  config.vm.define "nexus" do |nexus|
  	nexus.vm.box = "centos/7"
  	nexus.vm.provision "shell", path: "nexus.sh"
  	nexus.vm.network "private_network", ip: "192.168.33.50"
  	nexus.vm.network "forwarded_port", guest: 8081, host: 8081
  end

end
