Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell", path: "vagrant_provision.sh"
  config.vm.network "private_network", ip: "192.168.33.50"
  config.vm.network "forwarded_port", guest: 8081, host: 8081
end
